### PR TITLE
json updates for 1.3.2

### PR DESCRIPTION
**Pull request by enigmaquip**

### CODE REVIEW

**Comment by enigmaquip** [comment]
saved you some work :-)

**Comment by mrkite** [comment]
That's awesome.  I'm going to assume the map version changed too?

**Comment by enigmaquip** [comment]
yea, and the world file changed

**Comment by enigmaquip** [comment]
there's a few new header flags for 'party mode'

**Comment by mrkite** [comment]
Okay.. I'll fix those in a couple of hours.

**Pull request merged**
