### PR TITLE
New world file and version number

### PR DESCRIPTION
**Pull request by enigmaquip**

### CODE REVIEW

**Comment by enigmaquip** [comment]
That should be good to go now

**Comment by enigmaquip** [comment]
There's a new section after entities in the world file now (weighted pressure plate data), but don't think we really need to load it for mapping

**Comment by mrkite** [comment]
I'm loading it anyway (and just throwing it away).. just so future changes are a bit easier.

**Comment by mrkite** [comment]
Closing this PR because I already made the same changes you did.

Btw, it just occured to me that you might not have been using my handy dandy json editor:

http://seancode.com/terrafirma/editor/

It's not perfect, literally just something I threw together... but it helps a lot with adding stuff.

**Comment by enigmaquip** [comment]
Ooooh, did it all manually as I was making changes for the other program

**Pull request closed without merging**
